require File.join(File.dirname(__FILE__), 'components/text_view.rb')
require File.join(File.dirname(__FILE__), 'components/visual_component')
require File.join(File.dirname(__FILE__), 'components/window')
require File.join(File.dirname(__FILE__), 'patterns/structural/decorator/border_decorator')
require File.join(File.dirname(__FILE__), 'patterns/structural/decorator/decorator')
require File.join(File.dirname(__FILE__), 'patterns/structural/decorator/scroll_decorator')