require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/character')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/column')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/glyph')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/glyph_context')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/glyph_factory')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/row')
require File.join(File.dirname(__FILE__), 'patterns/structural/flyweight/editor/font')