require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/bus')
require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/cabinet')
require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/chassis')
require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/composite_equipment')
require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/equipment')
require File.join(File.dirname(__FILE__), 'patterns/structural/composite_adapter/equipments/floppy_disk')