require File.join(File.dirname(__FILE__), 'patterns/behaviors/chain_of_responsibility/help/application')
require File.join(File.dirname(__FILE__), 'patterns/behaviors/chain_of_responsibility/help/button')
require File.join(File.dirname(__FILE__), 'patterns/behaviors/chain_of_responsibility/help/dialog')
require File.join(File.dirname(__FILE__), 'patterns/behaviors/chain_of_responsibility/help/help_handler')
require File.join(File.dirname(__FILE__), 'patterns/behaviors/chain_of_responsibility/help/widget')